const DAILY_TASKS=[
 {id:'dress',text:'Get dressed',start:360,end:370,phase:'morning',reason:'Start with getting yourself ready.'},
 {id:'eat',text:'Eat something',start:370,end:380,phase:'morning',reason:'A little fuel can make the rest easier.'},
 {id:'meds',text:'Take medicines',start:380,end:385,phase:'morning',reason:'Take care of this before you head out.'},
 {id:'teeth',text:'Brush teeth',start:385,end:390,phase:'morning',reason:'Quick hygiene win.'},
 {id:'hair',text:'Do your hair',start:390,end:395,phase:'morning',reason:'Finish getting ready.'},
 {id:'leave',text:'Leave for work',start:395,end:420,phase:'morning',reason:'Give yourself enough time for the commute.'},
 {id:'sort',text:'Sort & plan your route',start:420,end:540,phase:'sorting',reason:'Figure out the workable plan—not a perfect one.'},
 {id:'deliver',text:'Work your route',start:540,end:720,phase:'delivery',reason:'One delivery at a time.'},
 {id:'lunch',text:'Lunch / reset',start:720,end:780,phase:'lunch',reason:'A real break helps you keep going.'},
 {id:'deliver2',text:'Continue your route',start:780,end:1050,phase:'delivery',reason:'Focus on the next stop.'},
 {id:'home',text:'Head home',start:1050,end:1080,phase:'transition',reason:'Work is almost behind you.'},
 {id:'pet',text:'Pet care',start:1080,end:1110,phase:'evening',reason:'Start with something concrete and quick.'},
 {id:'food',text:'Get food',start:1110,end:1140,phase:'evening',reason:'Take care of dinner before the evening gets away from you.'},
 {id:'hygiene',text:'Hygiene',start:1140,end:1170,phase:'evening',reason:'Take care of yourself.'},
 {id:'reset',text:'10-minute apartment reset',start:1170,end:1185,phase:'evening',reason:'Ten minutes is enough. Stop when the timer ends.'},
 {id:'tomorrow',text:'Prepare for tomorrow',start:1185,end:1200,phase:'evening',reason:'Make tomorrow morning a little easier.'},
 {id:'relax',text:'Relax',start:1200,end:1320,phase:'relax',reason:'Your responsibilities are done. This time is yours.'},
 {id:'wind',text:'Wind down',start:1320,end:1440,phase:'wind',reason:'Tomorrow can wait until tomorrow.'}
];
